// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

import type {
  GetServiceByIdQueryRequest,
  GetServiceByIdHeaderRequest,
  GetServiceById200Response,
  GetAllApisByServiceIdQueryRequest,
  GetAllApisByServiceIdHeaderRequest,
  GetAllApisByServiceId200Response,
  StartIterationBodyRequest,
  StartIterationHeaderRequest,
  StartIteration200Response,
  DeleteCategoryByIdBodyRequest,
  DeleteCategoryByIdHeaderRequest,
  DeleteCategoryById200Response,
  GenerateApiProposalBodyRequest,
  GenerateApiProposalHeaderRequest,
  GenerateApiProposal200Response,
  GetAllServicesQueryRequest,
  GetAllServicesHeaderRequest,
  GetAllServices200Response,
  GetHisNewestServicesByOwnerIdQueryRequest,
  GetHisNewestServicesByOwnerIdHeaderRequest,
  GetHisNewestServicesByOwnerId200Response,
  GetAllDeletedServicesByUserIdQueryRequest,
  GetAllDeletedServicesByUserIdHeaderRequest,
  GetAllDeletedServicesByUserId200Response,
  GetAllCategoriesByServiceIdQueryRequest,
  GetAllCategoriesByServiceIdHeaderRequest,
  GetAllCategoriesByServiceId200Response,
  GetHisMaintainedServicesByUserIdQueryRequest,
  GetHisMaintainedServicesByUserIdHeaderRequest,
  GetHisMaintainedServicesByUserId200Response,
  GetServiceByUuidAndVersionQueryRequest,
  GetServiceByUuidAndVersionHeaderRequest,
  GetServiceByUuidAndVersion200Response,
  IsServiceMaintainerQueryRequest,
  IsServiceMaintainerHeaderRequest,
  IsServiceMaintainer200Response,
  GetIterationByIdQueryRequest,
  GetIterationByIdHeaderRequest,
  GetIterationById200Response,
  ExportOpenapiByUuidAndVersionQueryRequest,
  ExportOpenapiByUuidAndVersionHeaderRequest,
  ExportOpenapiByUuidAndVersion200Response,
  GetAllVersionsByUuidQueryRequest,
  GetAllVersionsByUuidHeaderRequest,
  GetAllVersionsByUuid200Response,
  GetApiByIdQueryRequest,
  GetApiByIdHeaderRequest,
  GetApiById200Response,
  GetUserByUsernameOrNicknameOrEmailQueryRequest,
  GetUserByUsernameOrNicknameOrEmailHeaderRequest,
  GetUserByUsernameOrNicknameOrEmail200Response,
  UpdateApiCategoryByIdBodyRequest,
  UpdateApiCategoryByIdHeaderRequest,
  UpdateApiCategoryById200Response,
  CopyApiByApiDraftIdBodyRequest,
  CopyApiByApiDraftIdHeaderRequest,
  CopyApiByApiDraftId200Response,
  CreateNewServiceBodyRequest,
  CreateNewServiceHeaderRequest,
  CreateNewService200Response,
  DeleteServiceByIdBodyRequest,
  DeleteServiceByIdHeaderRequest,
  DeleteServiceById200Response,
  DeleteServicePermanentlyByIdBodyRequest,
  DeleteServicePermanentlyByIdHeaderRequest,
  DeleteServicePermanentlyById200Response,
  CommitIterationBodyRequest,
  CommitIterationHeaderRequest,
  CommitIteration200Response,
  DeleteApiByApiDraftIdBodyRequest,
  DeleteApiByApiDraftIdHeaderRequest,
  DeleteApiByApiDraftId200Response,
  UpdateDescriptionBodyRequest,
  UpdateDescriptionHeaderRequest,
  UpdateDescription200Response,
  AddOrRemoveServiceMaintainerByIdBodyRequest,
  AddOrRemoveServiceMaintainerByIdHeaderRequest,
  AddOrRemoveServiceMaintainerById200Response,
  RestoreServiceByIdBodyRequest,
  RestoreServiceByIdHeaderRequest,
  RestoreServiceById200Response,
  AddCategoryByServiceIdBodyRequest,
  AddCategoryByServiceIdHeaderRequest,
  AddCategoryByServiceId200Response,
  UpdateCategoryByIdBodyRequest,
  UpdateCategoryByIdHeaderRequest,
  UpdateCategoryById200Response,
  AddApiBodyRequest,
  AddApiHeaderRequest,
  AddApi200Response,
  DeleteIterationByIdBodyRequest,
  DeleteIterationByIdHeaderRequest,
  DeleteIterationById200Response,
  UpdateApiByApiDraftIdBodyRequest,
  UpdateApiByApiDraftIdHeaderRequest,
  UpdateApiByApiDraftId200Response,
} from './namespaces';

export default class CAMServiceService<T> {
  private request: any = () => {
    throw new Error('CAMServiceService.request is undefined');
  };
  private baseURL: string | ((path: string) => string) = '';

  constructor(options?: {
    baseURL?: string | ((path: string) => string);
    request?<R>(
      params: {
        url: string;
        method: 'GET' | 'POST' | 'PUT' | 'DELETE' | 'PATCH';
        data?: any;
        params?: any;
        headers?: any;
      },
      options?: T,
    ): Promise<R>;
  }) {
    this.request = options?.request || this.request;
    this.baseURL = options?.baseURL || this.baseURL;
  }

  private genBaseURL(path: string) {
    if (typeof this.baseURL === 'string') {
      const baseUrl = this.baseURL.trim().replace(/\/+$/, '');
      const apiPath = path.trim().replace(/^\/+/, '');
      return baseUrl + '/' + apiPath;
    }
    return this.baseURL(path);
  }

  /* API Services */

  /** 根据服务 ID 查询服务完整详情。 */
  GetServiceByIdGET(
    req: GetServiceByIdQueryRequest & GetServiceByIdHeaderRequest,
    options?: T,
  ): Promise<GetServiceById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getServiceById');
    const method = 'GET';
    const data = undefined;
    const params = { id: _req['id'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按服务和分类查询最新正式 API 简表，不返回请求和响应参数。 */
  GetAllApisByServiceIdGET(
    req: GetAllApisByServiceIdQueryRequest & GetAllApisByServiceIdHeaderRequest,
    options?: T,
  ): Promise<GetAllApisByServiceId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/getAllApisByServiceId');
    const method = 'GET';
    const data = undefined;
    const params = {
      service_id: _req['service_id'],
      category_id: _req['category_id'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 发起服务迭代，并将当前正式 API 与参数复制为草稿；当前用户已有未提交迭代时直接返回已有迭代 ID。 */
  StartIterationPOST(
    req: StartIterationBodyRequest & StartIterationHeaderRequest,
    options?: T,
  ): Promise<StartIteration200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/startIteration');
    const method = 'POST';
    const data = { service_id: _req['service_id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 删除指定 API 分类 */
  DeleteCategoryByIdPOST(
    req: DeleteCategoryByIdBodyRequest & DeleteCategoryByIdHeaderRequest,
    options?: T,
  ): Promise<DeleteCategoryById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/deleteCategoryById');
    const method = 'POST';
    const data = { category_id: _req['category_id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 根据自然语言生成不写入数据库的 API 草案，并校验迭代权限、参数合同、重复 API 和最多八层嵌套。 */
  GenerateApiProposalPOST(
    req: GenerateApiProposalBodyRequest & GenerateApiProposalHeaderRequest,
    options?: T,
  ): Promise<GenerateApiProposal200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/ai/generateApiProposal');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      prompt: _req['prompt'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 分页查询所有服务，只有 L0 用户可调用，结果包含已软删除服务 */
  GetAllServicesGET(
    req: GetAllServicesQueryRequest & GetAllServicesHeaderRequest,
    options?: T,
  ): Promise<GetAllServices200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getAllServices');
    const method = 'GET';
    const data = undefined;
    const params = {
      page_size: _req['page_size'],
      current_page: _req['current_page'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 分页查询指定所有者的未删除最新服务；查询自身时由令牌确定所有者。 */
  GetHisNewestServicesByOwnerIdGET(
    req: GetHisNewestServicesByOwnerIdQueryRequest &
      GetHisNewestServicesByOwnerIdHeaderRequest,
    options?: T,
  ): Promise<GetHisNewestServicesByOwnerId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getHisNewestServicesByOwnerId');
    const method = 'GET';
    const data = undefined;
    const params = {
      is_my_services: _req['is_my_services'],
      owner_id: _req['owner_id'],
      page_size: _req['page_size'],
      current_page: _req['current_page'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 分页查询当前用户已软删除服务 */
  GetAllDeletedServicesByUserIdGET(
    req: GetAllDeletedServicesByUserIdQueryRequest &
      GetAllDeletedServicesByUserIdHeaderRequest,
    options?: T,
  ): Promise<GetAllDeletedServicesByUserId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getAllDeletedServicesByUserId');
    const method = 'GET';
    const data = undefined;
    const params = {
      page_size: _req['page_size'],
      current_page: _req['current_page'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询指定服务下的全部 API 分类。 */
  GetAllCategoriesByServiceIdGET(
    req: GetAllCategoriesByServiceIdQueryRequest &
      GetAllCategoriesByServiceIdHeaderRequest,
    options?: T,
  ): Promise<GetAllCategoriesByServiceId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/getAllCategoriesByServiceId');
    const method = 'GET';
    const data = undefined;
    const params = { service_id: _req['service_id'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 分页查询用户作为维护者的未删除服务 */
  GetHisMaintainedServicesByUserIdGET(
    req: GetHisMaintainedServicesByUserIdQueryRequest &
      GetHisMaintainedServicesByUserIdHeaderRequest,
    options?: T,
  ): Promise<GetHisMaintainedServicesByUserId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getHisMaintainedServicesByUserId');
    const method = 'GET';
    const data = undefined;
    const params = {
      user_id: _req['user_id'],
      page_size: _req['page_size'],
      current_page: _req['current_page'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按服务 UUID 和版本查询服务快照；version 为 latest 时查询当前版本。 */
  GetServiceByUuidAndVersionGET(
    req: GetServiceByUuidAndVersionQueryRequest &
      GetServiceByUuidAndVersionHeaderRequest,
    options?: T,
  ): Promise<GetServiceByUuidAndVersion200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getServiceByUuidAndVersion');
    const method = 'GET';
    const data = undefined;
    const params = {
      service_uuid: _req['service_uuid'],
      version: _req['version'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 判断候选用户是否为指定服务维护者。 */
  IsServiceMaintainerGET(
    req: IsServiceMaintainerQueryRequest & IsServiceMaintainerHeaderRequest,
    options?: T,
  ): Promise<IsServiceMaintainer200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/isServiceMaintainer');
    const method = 'GET';
    const data = undefined;
    const params = {
      service_id: _req['service_id'],
      candidate_id: _req['candidate_id'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询未提交服务迭代的完整草稿信息；迭代已提交时返回业务错误。 */
  GetIterationByIdGET(
    req: GetIterationByIdQueryRequest & GetIterationByIdHeaderRequest,
    options?: T,
  ): Promise<GetIterationById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getIterationById');
    const method = 'GET';
    const data = undefined;
    const params = { id: _req['id'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按服务 UUID 和版本导出 OpenAPI 3.1.0 文档对象；version 为 latest 时导出当前版本。 */
  ExportOpenapiByUuidAndVersionGET(
    req: ExportOpenapiByUuidAndVersionQueryRequest &
      ExportOpenapiByUuidAndVersionHeaderRequest,
    options?: T,
  ): Promise<ExportOpenapiByUuidAndVersion200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/exportOpenapiByUuidAndVersion');
    const method = 'GET';
    const data = undefined;
    const params = {
      service_uuid: _req['service_uuid'],
      version: _req['version'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询服务当前及历史版本列表。 */
  GetAllVersionsByUuidGET(
    req: GetAllVersionsByUuidQueryRequest & GetAllVersionsByUuidHeaderRequest,
    options?: T,
  ): Promise<GetAllVersionsByUuid200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/getAllVersionsByUuid');
    const method = 'GET';
    const data = undefined;
    const params = { service_uuid: _req['service_uuid'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 查询正式 API 或草稿 API 的完整详情 */
  GetApiByIdGET(
    req: GetApiByIdQueryRequest & GetApiByIdHeaderRequest,
    options?: T,
  ): Promise<GetApiById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/getApiById');
    const method = 'GET';
    const data = undefined;
    const params = { api_id: _req['api_id'], is_latest: _req['is_latest'] };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 按用户名、昵称或邮箱模糊查询用户 */
  GetUserByUsernameOrNicknameOrEmailGET(
    req: GetUserByUsernameOrNicknameOrEmailQueryRequest &
      GetUserByUsernameOrNicknameOrEmailHeaderRequest,
    options?: T,
  ): Promise<GetUserByUsernameOrNicknameOrEmail200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/user/getUserByUsernameOrNicknameOrEmail');
    const method = 'GET';
    const data = undefined;
    const params = {
      username_or_nickname_or_email: _req['username_or_nickname_or_email'],
    };
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 修改正式 API 所属分类；category_id 传 -1 时取消分类。 */
  UpdateApiCategoryByIdPOST(
    req: UpdateApiCategoryByIdBodyRequest & UpdateApiCategoryByIdHeaderRequest,
    options?: T,
  ): Promise<UpdateApiCategoryById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/updateApiCategoryById');
    const method = 'POST';
    const data = { api_id: _req['api_id'], category_id: _req['category_id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 复制同一未提交迭代中的 API 草稿及其所有嵌套请求、响应参数。 */
  CopyApiByApiDraftIdPOST(
    req: CopyApiByApiDraftIdBodyRequest & CopyApiByApiDraftIdHeaderRequest,
    options?: T,
  ): Promise<CopyApiByApiDraftId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/copyApiByApiDraftId');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      api_draft_id: _req['api_draft_id'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 以当前用户为所有者创建服务，初始版本固定为 0.0.1。 */
  CreateNewServicePOST(
    req: CreateNewServiceBodyRequest & CreateNewServiceHeaderRequest,
    options?: T,
  ): Promise<CreateNewService200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/createNewService');
    const method = 'POST';
    const data = {
      service_uuid: _req['service_uuid'],
      description: _req['description'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 软删除指定服务的当前版本，历史迭代不删除。 */
  DeleteServiceByIdPOST(
    req: DeleteServiceByIdBodyRequest & DeleteServiceByIdHeaderRequest,
    options?: T,
  ): Promise<DeleteServiceById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/deleteServiceById');
    const method = 'POST';
    const data = { id: _req['id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 永久删除已软删除服务、全部正式 API、全部迭代、草稿 API 和关联参数。 */
  DeleteServicePermanentlyByIdPOST(
    req: DeleteServicePermanentlyByIdBodyRequest &
      DeleteServicePermanentlyByIdHeaderRequest,
    options?: T,
  ): Promise<DeleteServicePermanentlyById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/deleteServicePermanentlyById');
    const method = 'POST';
    const data = { id: _req['id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 提交草稿迭代，将草稿服务描述、API 和参数发布为当前正式版本。 */
  CommitIterationPOST(
    req: CommitIterationBodyRequest & CommitIterationHeaderRequest,
    options?: T,
  ): Promise<CommitIteration200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/commitIteration');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      new_version: _req['new_version'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 删除未提交迭代中的 API 草稿及其全部请求、响应参数。 */
  DeleteApiByApiDraftIdPOST(
    req: DeleteApiByApiDraftIdBodyRequest & DeleteApiByApiDraftIdHeaderRequest,
    options?: T,
  ): Promise<DeleteApiByApiDraftId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/deleteApiByApiDraftId');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      api_draft_id: _req['api_draft_id'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 更新未提交服务迭代的服务描述 */
  UpdateDescriptionPOST(
    req: UpdateDescriptionBodyRequest & UpdateDescriptionHeaderRequest,
    options?: T,
  ): Promise<UpdateDescription200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/updateDescription');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      description: _req['description'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 添加或移除维护者；候选用户已是维护者时移除，否则添加。 */
  AddOrRemoveServiceMaintainerByIdPOST(
    req: AddOrRemoveServiceMaintainerByIdBodyRequest &
      AddOrRemoveServiceMaintainerByIdHeaderRequest,
    options?: T,
  ): Promise<AddOrRemoveServiceMaintainerById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/addOrRemoveServiceMaintainerById');
    const method = 'POST';
    const data = {
      service_id: _req['service_id'],
      candidate_id: _req['candidate_id'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 恢复指定的已软删除服务。 */
  RestoreServiceByIdPOST(
    req: RestoreServiceByIdBodyRequest & RestoreServiceByIdHeaderRequest,
    options?: T,
  ): Promise<RestoreServiceById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/restoreServiceById');
    const method = 'POST';
    const data = { id: _req['id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 为指定服务新增 API 分类，同一服务下分类名称唯一。 */
  AddCategoryByServiceIdPOST(
    req: AddCategoryByServiceIdBodyRequest &
      AddCategoryByServiceIdHeaderRequest,
    options?: T,
  ): Promise<AddCategoryByServiceId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/addCategoryByServiceId');
    const method = 'POST';
    const data = {
      service_id: _req['service_id'],
      category_name: _req['category_name'],
      description: _req['description'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 更新指定 API 分类名称和说明 */
  UpdateCategoryByIdPOST(
    req: UpdateCategoryByIdBodyRequest & UpdateCategoryByIdHeaderRequest,
    options?: T,
  ): Promise<UpdateCategoryById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/updateCategoryById');
    const method = 'POST';
    const data = {
      category_id: _req['category_id'],
      category_name: _req['category_name'],
      description: _req['description'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 在未提交的服务迭代中创建 API 草稿。 */
  AddApiPOST(
    req: AddApiBodyRequest & AddApiHeaderRequest,
    options?: T,
  ): Promise<AddApi200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/addApi');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      name: _req['name'],
      method: _req['method'],
      path: _req['path'],
      description: _req['description'],
      level: _req['level'],
      category_id: _req['category_id'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 删除指定历史或草稿迭代，以及该迭代下的草稿 API 和参数 */
  DeleteIterationByIdPOST(
    req: DeleteIterationByIdBodyRequest & DeleteIterationByIdHeaderRequest,
    options?: T,
  ): Promise<DeleteIterationById200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/service/deleteIterationById');
    const method = 'POST';
    const data = { service_iteration_id: _req['service_iteration_id'] };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }

  /** 覆盖更新未提交 API 草稿的基本信息，并先删除后重建其请求和响应参数树。 */
  UpdateApiByApiDraftIdPOST(
    req: UpdateApiByApiDraftIdBodyRequest & UpdateApiByApiDraftIdHeaderRequest,
    options?: T,
  ): Promise<UpdateApiByApiDraftId200Response> {
    const _req = req || {};
    let url = this.genBaseURL('/v1/api/updateApiByApiDraftId');
    const method = 'POST';
    const data = {
      service_iteration_id: _req['service_iteration_id'],
      api_draft_id: _req['api_draft_id'],
      name: _req['name'],
      method: _req['method'],
      path: _req['path'],
      description: _req['description'],
      level: _req['level'],
      req_params: _req['req_params'],
      resp_params: _req['resp_params'],
    };
    const params = undefined;
    const headers = { Authorization: _req['Authorization'] };
    return this.request({ url, method, data, params, headers }, options);
  }
}
