// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck

export interface DeleteIterationByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface DeleteIterationByIdBodyRequest {
  /** 服务迭代 ID */
  service_iteration_id: number;
}

export interface DeleteIterationById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface UpdateApiByApiDraftIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface UpdateApiByApiDraftIdBodyRequest {
  /** 服务迭代 ID */
  service_iteration_id: number;
  /** 草稿 API ID */
  api_draft_id: number;
  /** API 名称 */
  name: string;
  /** HTTP 方法，枚举 GET、POST、PUT、DELETE、PATCH */
  method: string;
  /** API 路径 */
  path: string;
  /** API 描述 */
  description: string;
  /** API 等级，枚举 P0、P1、P2、P3、P4 */
  level: string;
  /** 序列化后的请求参数 JSON 数组 */
  req_params: string;
  /** 序列化后的响应参数 JSON 数组 */
  resp_params: string;
}

export interface UpdateApiByApiDraftId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface ImportOpenapiHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface ImportOpenapiBodyRequest {
  /** 目标服务 ID */
  service_id: number;
  /** 待导入的 OpenAPI JSON 文档 */
  openapi_object: any;
}

export interface ImportOpenapi200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 新建的导入迭代 ID */
  service_iteration_id: number;
  /** 导入的 API 数量 */
  api_count: number;
  /** 导入的请求参数总数（含嵌套参数） */
  request_param_count: number;
  /** 导入的响应参数总数（含嵌套参数） */
  response_param_count: number;
  /** 未阻断导入的兼容性提示 */
  warnings: string[];
}

export interface GetServiceByIdQueryRequest {
  /** 服务 ID */
  id: number;
}

export interface GetServiceByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetServiceById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 服务详情 */
  service: GetServiceById200ResponseService;
}

export interface GetServiceById200ResponseService {
  /** 正式 API 简表 */
  apis: any[];
  /** 服务迭代列表 */
  iterations: any[];
  /** 服务说明 */
  description: string | null;
  /** 创建时间（ISO 8601） */
  created_at: string;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 更新时间（ISO 8601） */
  updated_at: string;
  /** 服务所有者 ID */
  owner_id: number;
  /** 当前版本 */
  version: string;
  /** 维护者列表 */
  maintainers: GetServiceById200ResponseServiceMaintainersItem[];
  /** 服务 ID */
  id: number;
  /** API 分类列表 */
  api_categories: any[];
  /** 服务唯一标识 */
  service_uuid: string;
  /** 软删除时间 */
  deleted_at: string | null;
  /** 所有者信息 */
  owner: GetServiceById200ResponseServiceOwner;
}

export interface GetServiceById200ResponseServiceMaintainersItem {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname?: string | null;
  /** 邮箱 */
  email?: string | null;
  /** 角色 */
  role: string;
  /** 用户等级 */
  level: number;
  /** 用户创建时间 */
  created_at: string;
}

export interface GetServiceById200ResponseServiceOwner {
  /** 用户创建时间 */
  created_at: string;
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname?: string | null;
  /** 邮箱 */
  email?: string | null;
  /** 角色 */
  role: string;
  /** 用户等级 */
  level: number;
}

export interface GetAllApisByServiceIdQueryRequest {
  /** 服务 ID */
  service_id: number;
  /** API 分类 ID */
  category_id: number;
}

export interface GetAllApisByServiceIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetAllApisByServiceId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 正式 API 列表 */
  apis: GetAllApisByServiceId200ResponseApisItem[];
}

export interface GetAllApisByServiceId200ResponseApisItem {
  /** API 创建者 ID */
  owner_id: number;
  /** 所属分类 ID */
  category_id: number | null;
  /** API 名称 */
  name: string;
  /** API ID */
  id: number;
  /** HTTP 方法，枚举 GET、POST、PUT、DELETE、PATCH */
  method: string;
  /** API 路径 */
  path: string;
  /** API 描述 */
  description: string | null;
  /** API 等级，枚举 P0、P1、P2、P3、P4 */
  level: string;
  /** 所属服务 ID */
  service_id: number;
  /** 是否启用 */
  is_enabled: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}

export interface StartIterationHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface StartIterationBodyRequest {
  /** 服务 ID */
  service_id: number;
}

export interface StartIteration200Response {
  /** 新建迭代时的业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 新建或已有的迭代 ID */
  service_iteration_id: number;
}

export interface DeleteCategoryByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface DeleteCategoryByIdBodyRequest {
  /** 分类 ID */
  category_id: number;
}

export interface DeleteCategoryById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface GenerateApiProposalHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GenerateApiProposalBodyRequest {
  /** 未提交服务迭代 ID */
  service_iteration_id: number;
  /** 接口需求说明；不能为空且最大长度为 8000 个字符 */
  prompt: string;
}

export interface GenerateApiProposal200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 完整 API 草案；根节点必须且只能包含 add_api、req_params、resp_params */
  proposal:
    | GenerateApiProposal200ResponseProposal1
    | GenerateApiProposal200ResponseProposal2
    | GenerateApiProposal200ResponseProposal3;
}

export interface GenerateApiProposal200ResponseProposal1 {
  /** API 基本信息 */
  add_api: GenerateApiProposal200ResponseProposal1Add_api;
  /** 请求参数草案 */
  req_params: GenerateApiProposal200ResponseProposal1Req_paramsItem[];
  /** 响应参数草案 */
  resp_params: GenerateApiProposal200ResponseProposal1Resp_paramsItem[];
}

export interface GenerateApiProposal200ResponseProposal1Add_api {
  /** API 路径 */
  path: string;
  /** 英文 API 名称 */
  name: string;
  /** HTTP 方法 */
  method: string;
  /** API 描述 */
  description: string;
  /** API 等级 */
  level: string;
  /** 分类 ID */
  category_id: number | null;
}

export interface GenerateApiProposal200ResponseProposal1Req_paramsItem {
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 示例值 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 对象或对象数组的子参数 */
  children: any[] | null;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
}

export interface GenerateApiProposal200ResponseProposal1Resp_paramsItem {
  /** 字段类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 字段说明 */
  description: string | null;
  /** 字段示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 对象或对象数组的子字段 */
  children: any[] | null;
  /** HTTP 状态码 */
  status_code: number;
  /** 响应字段名称 */
  name: string;
}

export interface GenerateApiProposal200ResponseProposal2 {
  /** 缺失的字段· */
  missing_fields: string[];
}

export interface GenerateApiProposal200ResponseProposal3 {
  /** 已有的 API */
  duplicate_api: GenerateApiProposal200ResponseProposal3Duplicate_api;
  /** API 已存在，不能重复创建的提示 */
  message: string;
}

export interface GenerateApiProposal200ResponseProposal3Duplicate_api {
  method: string;
  path: string;
}

export interface GetAllServicesQueryRequest {
  /** 每页数量 */
  page_size?: number;
  /** 页码 */
  current_page?: number;
}

export interface GetAllServicesHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetAllServices200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 服务列表 */
  services: GetAllServices200ResponseServicesItem[];
  /** 全部服务总数 */
  total: number;
}

export interface GetAllServices200ResponseServicesItem {
  /** 创建时间 */
  created_at: string;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 删除时间 */
  deleted_at?: string | null;
  /** 所有者信息 */
  owner: GetAllServices200ResponseServicesItemOwner;
  /** 服务 ID */
  id: number;
  /** 服务唯一标识 */
  service_uuid: string;
  /** 版本 */
  version: string;
  /** 服务说明 */
  description?: string | null;
  /** 所有者 ID */
  owner_id: number;
}

export interface GetAllServices200ResponseServicesItemOwner {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetHisNewestServicesByOwnerIdQueryRequest {
  /** 是否查询当前用户服务 */
  is_my_services?: boolean;
  /** 目标所有者 ID */
  owner_id?: number;
  /** 每页数量 */
  page_size?: number;
  /** 页码 */
  current_page?: number;
}

export interface GetHisNewestServicesByOwnerIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetHisNewestServicesByOwnerId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 最新服务列表 */
  services: GetHisNewestServicesByOwnerId200ResponseServicesItem[];
  /** 服务总数 */
  total: number;
}

export interface GetHisNewestServicesByOwnerId200ResponseServicesItem {
  /** 创建时间 */
  created_at: string;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 服务 ID */
  id: number;
  /** 服务唯一标识 */
  service_uuid: string;
  /** 当前版本 */
  version: string;
  /** 服务说明 */
  description?: string | null;
  /** 所有者 ID */
  owner_id: number;
  /** 所有者信息，含 id:int、username:string、nickname:string|null、email:string|null、role:string、level:int、created_at:string(date-time) */
  owner?: GetHisNewestServicesByOwnerId200ResponseServicesItemOwner | null;
}

export interface GetHisNewestServicesByOwnerId200ResponseServicesItemOwner {
  /** 所有者 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 等级 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetAllDeletedServicesByUserIdQueryRequest {
  /** 每页数量 */
  page_size?: number;
  /** 页码 */
  current_page?: number;
}

export interface GetAllDeletedServicesByUserIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetAllDeletedServicesByUserId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 已删除服务列表 */
  deleted_services: GetAllDeletedServicesByUserId200ResponseDeleted_servicesItem[];
  /** 已删除服务总数 */
  total: number;
}

export interface GetAllDeletedServicesByUserId200ResponseDeleted_servicesItem {
  /** 服务版本 */
  version: string;
  /** 所有者 ID */
  owner_id: number;
  /** 创建时间 */
  created_at: string;
  /** 服务 ID */
  id: number;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 删除时间 */
  deleted_at: string | null;
  /** 服务唯一标识 */
  service_uuid: string;
  /** 服务说明 */
  description: string | null;
}

export interface GetAllCategoriesByServiceIdQueryRequest {
  /** 服务 ID */
  service_id: number;
}

export interface GetAllCategoriesByServiceIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetAllCategoriesByServiceId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** API 分类列表 */
  categories: GetAllCategoriesByServiceId200ResponseCategoriesItem[];
}

export interface GetAllCategoriesByServiceId200ResponseCategoriesItem {
  /** 分类 ID */
  id: number;
  /** 所属服务 ID */
  service_id: number;
  /** 分类名称 */
  name: string;
  /** 分类说明 */
  description: string | null;
}

export interface GetHisMaintainedServicesByUserIdQueryRequest {
  /** 维护者用户 ID，默认当前用户 ID */
  user_id?: number;
  /** 每页数量 */
  page_size?: number;
  /** 页码 */
  current_page?: number;
}

export interface GetHisMaintainedServicesByUserIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetHisMaintainedServicesByUserId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 维护的服务列表 */
  services: GetHisMaintainedServicesByUserId200ResponseServicesItem[];
  /** 服务总数 */
  total: number;
}

export interface GetHisMaintainedServicesByUserId200ResponseServicesItem {
  /** 创建时间 */
  created_at: string;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 服务 ID */
  id: number;
  /** 服务唯一标识 */
  service_uuid: string;
  /** 版本 */
  version: string;
  /** 服务说明 */
  description: string | null;
  /** 所有者 ID */
  owner_id: number;
  /** 所有者信息 */
  owner: GetHisMaintainedServicesByUserId200ResponseServicesItemOwner;
}

export interface GetHisMaintainedServicesByUserId200ResponseServicesItemOwner {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetServiceByUuidAndVersionQueryRequest {
  /** 服务唯一标识 */
  service_uuid: string;
  /** 服务版本或 latest */
  version: string;
}

export interface GetServiceByUuidAndVersionHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetServiceByUuidAndVersion200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 当前 Service 或历史 ServiceIteration 快照 */
  service: GetServiceByUuidAndVersion200ResponseService;
  /** 是否当前版本 */
  is_latest: boolean;
}

export interface GetServiceByUuidAndVersion200ResponseService {
  /** 服务 ID（仅历史版本返回） */
  service_id?: number;
  /** 迭代创建者 ID（仅历史版本返回） */
  creator_id?: number | null;
  /** 是否已发布（仅历史版本返回） */
  is_committed?: boolean;
  /** 迭代记录（仅当前版本返回） */
  iterations?: GetServiceByUuidAndVersion200ResponseServiceIterationsItem[];
  /** 迭代创建者（仅历史版本返回） */
  creator?: GetServiceByUuidAndVersion200ResponseServiceCreator;
  /** 服务 ID（当前版本）或迭代 ID（历史版本） */
  id: number;
  /** 所有者 ID（仅当前版本返回） */
  owner_id?: number;
  /** 服务唯一标识（仅当前版本返回） */
  service_uuid?: string;
  /** 服务版本（当前版本）或历史版本号（历史版本） */
  version: string | null;
  /** 服务说明（当前版本）或历史说明（历史版本） */
  description: string | null;
  /** 创建时间（当前版本）或迭代创建时间（历史版本） */
  created_at: string;
  /** 更新时间（仅当前版本返回） */
  updated_at?: string;
  /** 是否软删除（仅当前版本返回） */
  is_deleted?: boolean;
  /** 软删除时间（仅当前版本返回） */
  deleted_at: string | null;
  /** 所有者（仅当前版本返回） */
  owner?: GetServiceByUuidAndVersion200ResponseServiceOwner;
  /** 维护者列表（仅当前版本返回） */
  maintainers?: GetServiceByUuidAndVersion200ResponseServiceMaintainersItem[];
  /** API 分类（仅当前版本返回） */
  api_categories?: GetServiceByUuidAndVersion200ResponseServiceApi_categoriesItem[];
  /** 正式 API（仅当前版本返回） */
  apis?: GetServiceByUuidAndVersion200ResponseServiceApisItem[];
  /** 草稿 API 列表（仅历史版本返回） */
  api_drafts?: any[];
}

export interface GetServiceByUuidAndVersion200ResponseServiceIterationsItem {
  /** 迭代 ID */
  id: number;
  /** 迭代创建时间 */
  created_at: string;
  /** 是否已发布 */
  is_committed: boolean;
  /** 服务 ID */
  service_id: number;
  /** 迭代创建者 ID */
  creator_id?: number | null;
  /** 历史版本号 */
  version?: string | null;
  /** 历史说明 */
  description?: string | null;
}

export interface GetServiceByUuidAndVersion200ResponseServiceCreator {
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname?: string | null;
  /** 创建者 ID */
  id: number;
  /** 邮箱 */
  email?: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetServiceByUuidAndVersion200ResponseServiceOwner {
  /** 所有者 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname?: string | null;
  /** 邮箱 */
  email?: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetServiceByUuidAndVersion200ResponseServiceMaintainersItem {
  /** 维护者 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname?: string | null;
  /** 邮箱 */
  email?: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetServiceByUuidAndVersion200ResponseServiceApi_categoriesItem {
  /** 分类 ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 分类名称 */
  name: string;
  /** 分类描述 */
  description?: string | null;
}

export interface GetServiceByUuidAndVersion200ResponseServiceApisItem {
  /** 接口等级 */
  level: string;
  /** 请求路径 */
  path: string;
  /** API 描述 */
  description?: string | null;
  /** 是否启用 */
  is_enabled: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** API ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 所有者 ID */
  owner_id: number;
  /** 分类 ID */
  category_id?: number | null;
  /** API 名称 */
  name: string;
  /** 请求方法 */
  method: string;
}

export interface IsServiceMaintainerQueryRequest {
  /** 服务 ID */
  service_id: number;
  /** 候选用户 ID */
  candidate_id: number;
}

export interface IsServiceMaintainerHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface IsServiceMaintainer200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 候选用户是否为维护者 */
  is_current_maintainer: boolean;
}

export interface GetIterationByIdQueryRequest {
  /** 服务迭代 ID */
  id: number;
}

export interface GetIterationByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetIterationById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 服务迭代详情 */
  iteration: GetIterationById200ResponseIteration;
}

export interface GetIterationById200ResponseIteration {
  /** 创建者 */
  creator: GetIterationById200ResponseIterationCreator;
  /** 草稿 API 列表 */
  api_drafts: any[];
  /** 迭代 ID */
  id: number;
  /** 所属服务 ID */
  service_id: number;
  /** 迭代创建者 ID */
  creator_id: number | null;
  /** 提交后的版本号，未提交时为 null */
  version: string | null;
  /** 草稿服务说明 */
  description: string | null;
  /** 创建时间 */
  created_at: string;
  /** 是否已提交 */
  is_committed: boolean;
  /** 关联服务 */
  service: GetIterationById200ResponseIterationService;
}

export interface GetIterationById200ResponseIterationCreator {
  /** 用户名 */
  username: string;
  /** 等级 */
  level: number;
  /** 邮箱 */
  email: string | null;
  /** 创建时间 */
  created_at: string;
  /** 角色 */
  role: string;
  /** 昵称 */
  nickname: string | null;
  /** 用户 ID */
  id: number;
}

export interface GetIterationById200ResponseIterationService {
  /** 服务 ID */
  id: number;
  /** 所有者 ID */
  owner_id: number;
  /** 服务 UUID */
  service_uuid: string;
  /** 服务版本 */
  version: string;
  /** 服务描述 */
  description: string | null;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否已删除 */
  is_deleted: boolean;
  /** 删除时间 */
  deleted_at: string | null;
}

export interface ExportOpenapiByUuidAndVersionQueryRequest {
  /** 服务唯一标识 */
  service_uuid: string;
  /** 服务版本或 latest */
  version: string;
}

export interface ExportOpenapiByUuidAndVersionHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface ExportOpenapiByUuidAndVersion200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** OpenAPI 3.1.0 文档 */
  openapi_object: ExportOpenapiByUuidAndVersion200ResponseOpenapi_object;
  /** 是否当前版本 */
  is_latest: boolean;
}

export interface ExportOpenapiByUuidAndVersion200ResponseOpenapi_object {
  /** 路径定义 */
  paths: any;
  /** 可复用组件 */
  components: any;
  /** OpenAPI 规范版本 */
  openapi: string;
  /** 文档基础信息 */
  info: ExportOpenapiByUuidAndVersion200ResponseOpenapi_objectInfo;
}

export interface ExportOpenapiByUuidAndVersion200ResponseOpenapi_objectInfo {
  /** 服务名称 */
  title: string;
  /** 服务说明 */
  description: string | null;
  /** 文档版本 */
  version: string;
  /** 联系人信息 */
  contact: any | null;
}

export interface GetAllVersionsByUuidQueryRequest {
  /** 服务唯一标识 */
  service_uuid: string;
}

export interface GetAllVersionsByUuidHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetAllVersionsByUuid200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 版本列表 */
  versions: GetAllVersionsByUuid200ResponseVersionsItem[];
}

export interface GetAllVersionsByUuid200ResponseVersionsItem {
  /** 版本号 */
  version?: string | null;
  /** 是否当前版本 */
  is_latest: boolean;
}

export interface GetApiByIdQueryRequest {
  /** 正式 API ID 或草稿 API ID */
  api_id: number;
  /** 是否查询正式 API，false 时 api_id 表示草稿 API ID */
  is_latest?: boolean;
}

export interface GetApiByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface GetApiById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** API 详情 */
  api: GetApiById200ResponseApi;
}

export interface GetApiById200ResponseApi {
  /** 分类 ID */
  category_id: number | null;
  /** API ID */
  id: number;
  /** 所属服务 ID（is_latest 为 true 时必填） */
  service_id?: number;
  /** 所属服务迭代 ID（is_latest 为 false 时必填） */
  service_iteration_id?: number;
  /** API 所有者 ID */
  owner_id: number;
  /** API 名称 */
  name: string;
  /** HTTP 方法 */
  method: string;
  /** API 路径 */
  path: string;
  /** API 描述 */
  description: string | null;
  /** API 等级 */
  level: string;
  /** 是否启用 */
  is_enabled: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** API 所有者 */
  owner: GetApiById200ResponseApiOwner;
  /** 按 query、path、header、cookie、body 分组的请求参数 */
  request_params_by_location: GetApiById200ResponseApiRequest_params_by_location;
  /** 按状态码字符串分组的响应参数 */
  response_params_by_status_code: GetApiById200ResponseApiResponse_params_by_status_code;
}

export interface GetApiById200ResponseApiOwner {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 用户等级 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface GetApiById200ResponseApiRequest_params_by_location {
  /** query 位置请求参数 */
  query: GetApiById200ResponseApiRequest_params_by_locationQueryItem[];
  /** path 位置请求参数 */
  path: GetApiById200ResponseApiRequest_params_by_locationPathItem[];
  /** header 位置请求参数 */
  header: GetApiById200ResponseApiRequest_params_by_locationHeaderItem[];
  /** cookie 位置请求参数 */
  cookie: GetApiById200ResponseApiRequest_params_by_locationCookieItem[];
  /** body 位置请求参数 */
  body: GetApiById200ResponseApiRequest_params_by_locationBodyItem[];
}

export interface GetApiById200ResponseApiRequest_params_by_locationQueryItem {
  /** 请求参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 参数示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父参数 ID */
  parent_param_id: number | null;
  /** 对象或对象数组的子参数 */
  children_params: any[] | null;
}

export interface GetApiById200ResponseApiRequest_params_by_locationPathItem {
  /** 请求参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 参数示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父参数 ID */
  parent_param_id: number | null;
  /** 对象或对象数组的子参数 */
  children_params: any[] | null;
}

export interface GetApiById200ResponseApiRequest_params_by_locationHeaderItem {
  /** 请求参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 参数示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父参数 ID */
  parent_param_id: number | null;
  /** 对象或对象数组的子参数 */
  children_params: any[] | null;
}

export interface GetApiById200ResponseApiRequest_params_by_locationCookieItem {
  /** 请求参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 参数示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父参数 ID */
  parent_param_id: number | null;
  /** 对象或对象数组的子参数 */
  children_params: any[] | null;
}

export interface GetApiById200ResponseApiRequest_params_by_locationBodyItem {
  /** 请求参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** 参数名称 */
  name: string;
  /** 参数位置，枚举 query、path、header、cookie、body */
  location: string;
  /** 参数类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 默认值 */
  default_value: string | null;
  /** 参数说明 */
  description: string | null;
  /** 参数示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父参数 ID */
  parent_param_id: number | null;
  /** 对象或对象数组的子参数 */
  children_params: any[] | null;
}

export interface GetApiById200ResponseApiResponse_params_by_status_code {
  /** HTTP 状态码 200 的响应参数 */
  200: GetApiById200ResponseApiResponse_params_by_status_code200Item[];
}

export interface GetApiById200ResponseApiResponse_params_by_status_code200Item {
  /** 响应参数 ID */
  id: number;
  /** 所属正式 API ID */
  api_id?: number;
  /** 所属草稿 API ID */
  api_draft_id?: number;
  /** HTTP 响应状态码 */
  status_code: number;
  /** 响应字段名称 */
  name: string;
  /** 响应字段类型，枚举 string、int、double、boolean、array、object、binary */
  type: string;
  /** 是否必填 */
  required: boolean;
  /** 是否允许 JSON null */
  nullable: boolean;
  /** 字段说明 */
  description: string | null;
  /** 字段示例 */
  example: string | null;
  /** 数组元素类型 */
  array_child_type: string | null;
  /** 父字段 ID */
  parent_param_id: number | null;
  /** 对象或对象数组子字段 */
  children_params: any[] | null;
}

export interface GetUserByUsernameOrNicknameOrEmailQueryRequest {
  /** 用户名、昵称或邮箱关键字 */
  username_or_nickname_or_email: string;
}

export interface GetUserByUsernameOrNicknameOrEmailHeaderRequest {
  /** 身份验证令牌 */
  Authorization: string;
}

export interface GetUserByUsernameOrNicknameOrEmail200Response {
  /** 响应状态码 */
  status: number;
  /** 响应提示信息 */
  message: string;
  /** 用户列表 */
  users: GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem[];
}

export interface GetUserByUsernameOrNicknameOrEmail200ResponseUsersItem {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 用户角色 */
  role: string;
  /** 用户级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface UpdateApiCategoryByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface UpdateApiCategoryByIdBodyRequest {
  /** 正式 API ID */
  api_id: number;
  /** 目标分类 ID；-1 代表未分类 */
  category_id: number;
}

export interface UpdateApiCategoryById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface CopyApiByApiDraftIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface CopyApiByApiDraftIdBodyRequest {
  /** 服务迭代 ID */
  service_iteration_id: number;
  /** 待复制草稿 API ID */
  api_draft_id: number;
}

export interface CopyApiByApiDraftId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface CreateNewServiceHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface CreateNewServiceBodyRequest {
  /** 服务唯一标识 */
  service_uuid: string;
  /** 服务说明 */
  description: string;
}

export interface CreateNewService200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 新建服务详情 */
  service: CreateNewService200ResponseService;
}

export interface CreateNewService200ResponseService {
  /** 服务 ID */
  id: number;
  /** 服务所有者 ID */
  owner_id: number;
  /** 服务唯一标识 */
  service_uuid: string;
  /** 初始版本 */
  version: string;
  /** 服务说明 */
  description: string | null;
  /** 迭代列表 */
  iterations: CreateNewService200ResponseServiceIterationsItem[];
  /** 所有者 */
  owner: CreateNewService200ResponseServiceOwner;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** 是否软删除 */
  is_deleted: boolean;
  /** 删除时间 */
  deleted_at: string | null;
  /** 维护者列表 */
  maintainers: CreateNewService200ResponseServiceMaintainersItem[];
  /** 分类列表 */
  api_categories: CreateNewService200ResponseServiceApi_categoriesItem[];
  /** API 列表 */
  apis: CreateNewService200ResponseServiceApisItem[];
}

export interface CreateNewService200ResponseServiceIterationsItem {
  /** 迭代 ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 创建者 ID */
  creator_id: number | null;
  /** 版本号 */
  version: string | null;
  /** 描述 */
  description: string | null;
  /** 创建时间 */
  created_at: string;
  /** 是否提交 */
  is_committed: boolean;
}

export interface CreateNewService200ResponseServiceOwner {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface CreateNewService200ResponseServiceMaintainersItem {
  /** 用户 ID */
  id: number;
  /** 用户名 */
  username: string;
  /** 昵称 */
  nickname: string | null;
  /** 邮箱 */
  email: string | null;
  /** 角色 */
  role: string;
  /** 级别 */
  level: number;
  /** 创建时间 */
  created_at: string;
}

export interface CreateNewService200ResponseServiceApi_categoriesItem {
  /** 分类 ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 分类名称 */
  name: string;
  /** 分类说明 */
  description: string | null;
}

export interface CreateNewService200ResponseServiceApisItem {
  /** 分类 ID */
  category_id: number | null;
  /** API 名称 */
  name: string;
  /** 请求方法 */
  method: string;
  /** 路径 */
  path: string;
  /** 描述 */
  description: string | null;
  /** 等级 */
  level: string;
  /** 是否启用 */
  is_enabled: boolean;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
  /** API ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 所有者 ID */
  owner_id: number;
}

export interface DeleteServiceByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface DeleteServiceByIdBodyRequest {
  /** 服务 ID */
  id: number;
}

export interface DeleteServiceById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface DeleteServicePermanentlyByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface DeleteServicePermanentlyByIdBodyRequest {
  /** 已软删除服务 ID */
  id: number;
}

export interface DeleteServicePermanentlyById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface CommitIterationHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface CommitIterationBodyRequest {
  /** 待提交迭代 ID */
  service_iteration_id: number;
  /** 新服务版本，不能等于当前版本 */
  new_version: string;
}

export interface CommitIteration200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 正式服务 ID */
  service_id: number;
  /** 已提交迭代 ID */
  service_iteration_id: number;
  /** 已发布版本 */
  version: string;
}

export interface DeleteApiByApiDraftIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface DeleteApiByApiDraftIdBodyRequest {
  /** 服务迭代 ID */
  service_iteration_id: number;
  /** 待删除草稿 API ID */
  api_draft_id: number;
}

export interface DeleteApiByApiDraftId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface UpdateDescriptionHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface UpdateDescriptionBodyRequest {
  /** 服务迭代 ID */
  service_iteration_id: number;
  /** 更新后的服务描述 */
  description: string;
}

export interface UpdateDescription200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface AddOrRemoveServiceMaintainerByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface AddOrRemoveServiceMaintainerByIdBodyRequest {
  /** 服务 ID */
  service_id: number;
  /** 候选用户 ID */
  candidate_id: number;
}

export interface AddOrRemoveServiceMaintainerById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 切换后的维护者状态 */
  is_current_maintainer: boolean;
}

export interface RestoreServiceByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface RestoreServiceByIdBodyRequest {
  /** 服务 ID */
  id: number;
}

export interface RestoreServiceById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
}

export interface AddCategoryByServiceIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface AddCategoryByServiceIdBodyRequest {
  /** 服务 ID */
  service_id: number;
  /** 分类名称 */
  category_name: string;
  /** 分类说明 */
  description: string | null;
}

export interface AddCategoryByServiceId200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 新建分类 */
  category: AddCategoryByServiceId200ResponseCategory;
}

export interface AddCategoryByServiceId200ResponseCategory {
  /** 分类 ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 分类名称 */
  name: string;
  /** 分类说明 */
  description: string | null;
}

export interface UpdateCategoryByIdHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface UpdateCategoryByIdBodyRequest {
  /** 分类 ID */
  category_id: number;
  /** 更新后的分类名称 */
  category_name: string | null;
  /** 更新后的分类说明 */
  description: string | null;
}

export interface UpdateCategoryById200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 更新后的分类 */
  category: UpdateCategoryById200ResponseCategory;
}

export interface UpdateCategoryById200ResponseCategory {
  /** 分类 ID */
  id: number;
  /** 服务 ID */
  service_id: number;
  /** 分类名称 */
  name: string;
  /** 分类说明 */
  description?: string | null;
}

export interface AddApiHeaderRequest {
  /** Bearer 访问令牌 */
  Authorization: string;
}

export interface AddApiBodyRequest {
  /** 未提交服务迭代 ID */
  service_iteration_id: number;
  /** API 名称 */
  name: string;
  /** HTTP 方法，枚举 GET、POST、PUT、DELETE、PATCH */
  method: string;
  /** API 路径 */
  path: string;
  /** API 描述 */
  description: string;
  /** API 等级，枚举 P0、P1、P2、P3、P4 */
  level: string;
  /** API 分类 ID */
  category_id?: number | null;
}

export interface AddApi200Response {
  /** 业务状态码 */
  status: number;
  /** 响应信息 */
  message: string;
  /** 新建 API 草稿 */
  api: AddApi200ResponseApi;
}

export interface AddApi200ResponseApi {
  /** 草稿 API ID */
  id: number;
  /** 草稿创建者 ID */
  owner_id: number;
  /** 分类 ID */
  category_id?: number | null;
  /** API 名称 */
  name: string;
  /** HTTP 方法 */
  method: string;
  /** API 路径 */
  path: string;
  /** API 等级 */
  level: string;
  /** API 描述 */
  description?: string | null;
  /** 是否启用 */
  is_enabled: boolean;
  /** 服务迭代 ID */
  service_iteration_id: number;
  /** 创建时间 */
  created_at: string;
  /** 更新时间 */
  updated_at: string;
}
